# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Bundler::ConnectionPool::ForkTracker; end
module T::Private::Methods::Signature; end
module Types::Params::Time; end
module Types::String; end
